blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: 🐛 Bug Report
    description: Report something that isn't working as expected
    file: bug_report.md
  - name: 🚀 Feature Request
    description: Suggest an idea for this project
    file: feature_request.md
  - name: 📖 Documentation
    description: Report missing or unclear documentation
    file: documentation.md
  - name: 🔧 Enhancement
    description: Propose improvement to existing features
    file: enhancement.md
  - name: 💬 Other
    description: Ask a general question or other topic
    file: other.md
