name: Self Assign Issue

on:
  issues:
    types:
      - opened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check for /assignme command in issue body
        id: check_body
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          script: |
            const body = context.payload.issue.body;
            const assignUsing = '/assignme';
            const issueAssignees = context.payload.issue.assignees.map(a => a.login);
            const hasAssignees = issueAssignees.length > 0;
            const opener = context.payload.issue.user.login;

            if (!body.includes(assignUsing)) {
              console.log('No /assignme command found in the issue body.');
              return core.setOutput('toAssign', 'false');
            }

            if (hasAssignees && issueAssignees.includes(opener)) {
              console.log('Issue already assigned to opener.');
              return core.setOutput('toAssign', 'false');
            }

            if (hasAssignees) {
              const { owner, repo, number } = context.issue;
              const msg = `Hey @${opener}, the issue is already assigned to someone else. Please feel free to contribute to another issue or create a new one.`;
              await github.issues.createComment({ owner, repo, issue_number: number, body: msg });
              return core.setOutput('toAssign', 'false');
            }

            core.setOutput('toAssign', 'true');
            core.setOutput('assignee', opener);

      - name: Assign issue to creator
        if: steps.check_body.outputs.toAssign == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const assignee = '${{ steps.check_body.outputs.assignee }}';
            await github.issues.addAssignees({
              owner,
              repo,
              issue_number: number,
              assignees: [assignee]
            });
            console.log(`Issue assigned to ${assignee}.`);
